### PR TITLE
Downgrade 9 and 10 to bullseye

### LINKED ISSUE #93: apt is broken for some gcc images
The `gcc:10-bookworm` image seems to be broken:
```bash
$ docker run --rm -it gcc:10-bookworm apt --version
apt: /usr/local/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libapt-private.so.0.0)
apt: /usr/local/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libapt-pkg.so.6.0)
```

Although other variations seem ok:

```bash
$ docker run --rm -it gcc:10-buster apt --version
apt 1.8.2.3 (amd64)
```

```bash
$ docker run --rm -it gcc:11-bookworm apt --version
apt 2.6.1 (amd64)
```

### PR DESCRIPTION
**Pull request by yosifkit**
Add smoke test to help prevent the same error
```console
$ apt-get --version
apt-get: /usr/local/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libapt-private.so.0.0)
apt-get: /usr/local/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libapt-pkg.so.6.0)
```

Fixes #93

### CODE REVIEW

File: versions.sh [hunk 1]
```diff
@@ -3,6 +3,11 @@ set -Eeuo pipefail
 
 # defaultDebianSuite gets auto-declared below
 declare -A debianSuites=(
+# the libc created by gcc is too old for a newer Debian
+# $ apt --version
+# apt: /usr/local/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found
+	[10]="bullseye"
+	[9]="bullseye"
```
Comment (tianon) [inline versions.sh:10]:
```suggestion
	[10]='bullseye'
	[9]='bullseye'
```

(I think I'm going to apply this post-merge so we don't have to wait for CI again :upside_down_face:)
